# Generated by Django 5.1.1 on 2024-11-13 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0004_rename_name_product_artist_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='genre',
        ),
    ]
