# Generated by Django 5.1.1 on 2024-11-13 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0005_remove_product_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='search_app.category'),
        ),
    ]
