# Generated by Django 5.1.1 on 2024-11-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0009_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
