# Generated by Django 5.1.1 on 2024-11-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0011_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='media/'),
        ),
    ]
