# Generated by Django 5.1.1 on 2024-11-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0012_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.png', upload_to='media/'),
        ),
    ]
