# Generated by Django 5.1.1 on 2024-12-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0015_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='album',
            field=models.CharField(default='アルバム情報がありません', max_length=255),
        ),
    ]
